Hibernate intro
Ketch92/cinema pull request #1
Opened 2021-01-26 12:43 UTC by Ketch92

2021-01-26 15:26 UTC, gigbat requested changes

2021-01-26 15:26 UTC, gigbat commented on src/main/java/core/Main.java
> +
```suggestion
        movie.setTitle("Fast and Furious");
        movieService.add(movie);
```

2021-01-26 15:26 UTC, gigbat commented on src/main/java/core/dao/MovieDaoImpl.java
> +        Transaction transaction = null;
unused operation here

2021-01-26 15:29 UTC, Ketch92 commented on src/main/java/core/Main.java
> +
LOL

2021-01-26 15:29 UTC, Ketch92 commented on src/main/java/core/dao/MovieDaoImpl.java
> +        Transaction transaction = null;
True

2021-01-26 15:30 UTC, gigbat approved these changes

2021-01-27 08:20 UTC, Sofasmile requested changes

2021-01-27 08:20 UTC, Sofasmile commented on src/main/java/core/Main.java
> +        movie.setTitle("Fast and Furious");
let's test add() method here

2021-01-27 08:20 UTC, Sofasmile commented on src/main/java/core/service/MovieServiceImpl.java
> +    private MovieDao dao;
```suggestion
    private MovieDao movieDao;
```

2021-01-27 08:26 UTC, Ketch92 commented on src/main/java/core/Main.java
> +        movie.setTitle("Fast and Furious");
Somehow I removed it, Thanks

2021-01-27 11:00 UTC, RomanDubovskyi approved these changes

2021-01-31 10:14 UTC, merged