Hb session and cinema hall
Ketch92/cinema pull request #2
Opened 2021-02-01 11:01 UTC by Ketch92

2021-02-01 13:27 UTC, Fedich09 requested changes

2021-02-01 13:27 UTC, Fedich09 commented on src/main/java/core/dao/impl/CinemaHallDaoImpl.java
> +            if (transaction != null || transaction.isActive()) {
```suggestion
            if (transaction != null || transaction.isActive()) {
```
I think, we should use here && instead of ||

2021-02-01 13:27 UTC, Fedich09 commented on src/main/java/core/dao/impl/MovieSessionDaoImpl.java
> +            if (transaction != null || transaction.isActive()) {
```suggestion
            if (transaction != null || transaction.isActive()) {
```
same mistake here)

2021-02-02 08:25 UTC, dmytro-hryhoruk approved these changes
Good job!

2021-02-02 08:25 UTC, dmytro-hryhoruk commented on src/main/java/core/dao/impl/MovieSessionDaoImpl.java
> +                            date.atTime(LocalTime.of(23, 59, 59)));
use constant LocalTime.MAX

2021-02-02 08:25 UTC, dmytro-hryhoruk commented on src/main/java/core/dao/impl/MovieSessionDaoImpl.java
> +                            date.atTime(LocalTime.now()));
```suggestion
                            date.atStartOfDay();
```

2021-02-02 08:37 UTC, dmytro-hryhoruk reviewed
fix compilation

2021-02-02 09:50 UTC, Ketch92 commented on src/main/java/core/dao/impl/MovieSessionDaoImpl.java
> +                            date.atTime(LocalTime.of(23, 59, 59)));
Thanks. Nice tip

2021-02-02 09:53 UTC, merged